version: '3.8'

services:
  app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5437:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app

  # Optional NGINX reverse proxy (useful for production)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
